[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask",
    "psycopg2-binary",
    "werkzeug",
    "flask-mail",
    "bcrypt",
    "google-auth-oauthlib",
    "requests",
]